# Configuration for Label Actions - https://github.com/dessant/label-actions

incomplete:
  issues:
    comment: >
      @{issue-author}, the issue does not contain enough information
      to reproduce the bug. Please open a new bug report and describe
      the issue in detail.
    close: true
